### ISSUE TITLE
Latest gcc version needs -gdwarf-4 switch

### ISSUE THREAD

**Issue by jpmattia** [ssbssa/dwarfstack#3]
We updated our MinGW installation somewhat recently, and noticed that stack traces (based on dwarfstack) stopped working. We traced it to the compile switches: The latest version of gcc needs -gdwarf-4 during compilation.

The issue can be replicated by cloning this repo, and compiling the example "exception". As written, the file info will be omitted from the stack trace.  Change "-g" to "-gdwarf-4", recompile, and the file info will be visible in the stack trace.

The gcc version info used was:
```
% gcc --version
gcc.exe (Rev10, Built by MSYS2 project) 12.2.0
```

In any case: Thanks for this repo, it has been helpful.

**Comment by ssbssa** [comment]
Which version of dwarfstack are you using?
Latest git should work with dwarf 5.

**Comment by jpmattia** [comment]
We cloned the repo today, then:

1.  "make" at the top level
2.  cd examples/exception
3. "make" again
4.  ran "./exception.exe"

and the file info was not present.

The msys2 environment also has [a version compiled March 2022](https://packages.msys2.org/package/mingw-w64-x86_64-dwarfstack?repo=mingw64). I'm pretty sure that the steps 1-4 result in the just-compiled library being used (and not the MSYS2- installed version), but if there's a way to confirm, let me know.

**Comment by ssbssa** [comment]
I just now updated to latest MSYS2 gcc (gcc version 13.1.0 (Rev5, Built by MSYS2 project)), and did the exact same steps as you just described, and after copying the dwarfstack.dll to the examples/exception directory, got this output:
```
application crashed
code: 0xC0000005 (ACCESS_VIOLATION)
write access violation at 0x0000000000001234
base address: 0x000000013f790000 (exception.exe)
    stack 00: 0x000000013f791a00 (crasher.c:10:6) [crasher]
    stack 01: 0x000000013f79811e (exception.c:112:3) [d]
                                 (exception.c:117:3) [c]
                                 (exception.c:122:3) [b]
                                 (exception.c:127:3) [a]
                                 (exception.c:134:3) [main]
    stack 02: 0x000000013f7912ed (crtexe.c:272:15) [__tmainCRTStartup]
```
Did you check that the newly built dwarfstack.dll is actually used by exception.exe?
Maybe you have an old version still somewhere in your $PATH.

**Comment by jpmattia** [comment]
Hmm. I copied the dll to the local dir in examples/exception, then issued the command directly

```
% gcc -O3 -gdwarf-5 -Wall -Wextra -I../../include -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-schedule-insns2 -o exception.exe exception.c crasher.c ./dwarfstack.dll

% ./exception.exe
application crashed
code: 0xC0000005 (ACCESS_VIOLATION)
write access violation at 0x0000000000001234
base address: 0x00007ff7f48b0000 (exception.exe)

Now abort() in libdwarf. No error argument or handler available.
```

I'm willing to guess there is an inconsistency in my msys2 installation, especially since you just checked it, so feel free to close this off and I'll double-check it when I'm able to do a complete msys2 update.

Also: Many thanks for your help.

**Comment by ssbssa** [comment]
I'd rather figure out what the problem is here.
You can try my build of exception.exe/dwarstack.dll here: [exception.zip](https://github.com/ssbssa/dwarfstack/files/11455675/exception.zip)
Maybe you also upload yours here, and I'll try it.

**Comment by jpmattia** [comment]
There is definitely an old version of dwarfstack on my machine. Before trying your zip file, I just did 
```
% cp ../../bin/dwarfstack.dll .
% % gcc -O3 -gdwarf-5 -Wall -Wextra -I../../include -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-schedule-insns2 -o exception.exe exception.c crasher.c ./dwarfstack.dll
```
and the result was:

```
% ./exception.exe
application crashed
code: 0xC0000005 (ACCESS_VIOLATION)
write access violation at 0x0000000000001234
base address: 0x00007ff74ae90000 (exception.exe)
    stack 00: 0x00007ff74ae91a50 (crasher.c:10:6) [crasher]
    stack 01: 0x00007ff74ae9815e (exception.c:112:3) [d]
                                 (exception.c:117:3) [c]
                                 (exception.c:122:3) [b]
                                 (exception.c:127:3) [a]
                                 (exception.c:134:3) [main]
    stack 02: 0x00007ff74ae912ed (crtexe.c:272:15) [__tmainCRTStartup]
Segmentation fault

```
Since that dll is the one I compiled when opening the issue, I'm pretty sure the answer is that my environment is defaulting to an old version.

**Comment by ssbssa** [comment]
Ok, I thought it had to be something like this.
Maybe I should just make a release from the current git version (I never bothered because I wasn't aware that people besides me actually use it).

**Comment by jpmattia** [comment]
I think it's a great repo, and avoids the hassle of some other implementations which need cv2pdb. 

I guess my suggestion would be to add a note about supporting dwarf-5 in the README, in case anyone else is in my boat and needs to be hit over the head with a sledgehammer to double check which dll is actually being used. :)

**Comment by ssbssa** [comment]
May I ask how you use dwarfstack?
You mentioned cv2pdb, which is usually needed for programs that only understand PDB symbols.

**Comment by jpmattia** [comment]
Our use is crash analysis for a downloading service running under windows. As for cv2pdb, it would be a step in an alternative approach, as mentioned [here.](https://theorangeduck.com/page/printing-stack-trace-mingw)

**Comment by ssbssa** [comment]
I guess I prefer minidumps for crash analysis, usually stack traces are only enough for the obvious crash reasons.
